# Generated by Django 3.0.4 on 2020-03-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_cover', models.ImageField(blank=True, null=True, upload_to='manga_covers/')),
                ('manga_cover_url', models.CharField(blank=True, max_length=256, null=True)),
                ('manga_name', models.CharField(max_length=60)),
                ('manga_other_names', models.CharField(max_length=60)),
                ('manga_authors', models.CharField(max_length=120)),
                ('manga_status', models.CharField(max_length=40)),
                ('manga_views', models.PositiveIntegerField(default=0)),
                ('manga_genres', models.TextField()),
                ('manga_descrition', models.TextField()),
                ('manga_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(max_length=10)),
                ('chapter_added', models.DateTimeField(auto_now_add=True)),
                ('chapter_links', models.TextField()),
                ('chapter_slug', models.SlugField(unique=True)),
                ('chapter_manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga')),
            ],
        ),
    ]
