# Generated by Django 3.0.4 on 2020-04-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20200331_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='manga',
            name='manga_other_names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
