# Generated by Django 3.0.4 on 2020-04-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_auto_20200404_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='manga_other_names',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='manga_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
