# Generated by Django 3.0.4 on 2020-04-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_auto_20200404_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.CharField(max_length=1024),
        ),
    ]
