# Generated by Django 3.0.4 on 2020-04-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_auto_20200405_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_cover_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='manga_other_names',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
