# Generated by Django 3.0.4 on 2020-04-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_auto_20200406_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_authors',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='manga',
            name='manga_name',
            field=models.CharField(max_length=1024),
        ),
    ]
