# Generated by Django 3.0.4 on 2020-04-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_auto_20200413_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ch_url', models.URLField(default='hello')),
                ('image_ch', models.ImageField(upload_to='chapter_content/')),
                ('image_chx', models.CharField(default='hello', max_length=10000)),
                ('chapter_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.chapter')),
            ],
        ),
    ]
