# Generated by Django 3.0.5 on 2020-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_auto_20200426_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
