# Generated by Django 3.0.5 on 2020-04-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manga', '0007_auto_20200413_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_one', models.PositiveIntegerField(default=0, null=True)),
                ('rate_two', models.PositiveIntegerField(default=0, null=True)),
                ('rate_three', models.PositiveIntegerField(default=0, null=True)),
                ('rate_four', models.PositiveIntegerField(default=0, null=True)),
                ('rate_five', models.PositiveIntegerField(default=0, null=True)),
                ('rate_manga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manga.manga')),
            ],
        ),
        migrations.CreateModel(
            name='ip_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_of_rater', models.CharField(max_length=30)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rateit.rate')),
            ],
        ),
    ]
