# Generated by Django 3.0.5 on 2020-04-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateit', '0002_ip_rate_his_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rate_five',
            new_name='hearts',
        ),
        migrations.RemoveField(
            model_name='ip_rate',
            name='his_vote',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='rate_four',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='rate_one',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='rate_three',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='rate_two',
        ),
    ]
